const express = require('express')
const router = express.Router()
const consultaController = require('../controllers/consultaController')
const authMiddleware = require('../middlewares/authMiddleware')
const validate = require('../middlewares/validate')
const consultaValidator = require('../validators/consultaValidator')

router.use(authMiddleware)

router.get('/', consultaController.listar)
router.get('/total-agendadas', consultaController.totalAgendadas)
router.get('/pendentes', consultaController.consultasPendentes)
router.get('/:id', consultaController.buscarPorId)
router.post('/', validate(consultaValidator.criar), consultaController.criar)
router.patch('/:id', validate(consultaValidator.atualizar), consultaController.atualizar)
router.patch('/:id/confirmar', consultaController.confirmar)
router.patch('/:id/status', consultaController.atualizarStatus)
router.patch('/:id/cancelar', consultaController.cancelar)
router.delete('/:id', consultaController.excluir)   
module.exports = router
